"""sprint3_monitor_id_monitor_salary_api_key

Revision ID: 32a23eb74df2
Revises: 6cbb30dacf33
Create Date: 2026-04-22 17:39:00.293163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32a23eb74df2'
down_revision: Union[str, None] = '6cbb30dacf33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=512), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_prefix'), 'api_keys', ['prefix'], unique=False)
    op.create_index(op.f('ix_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('monitor_salaries',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.Column('amount_cop', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitor_salaries_effective_from'), 'monitor_salaries', ['effective_from'], unique=False)
    op.create_index(op.f('ix_monitor_salaries_monitor_id'), 'monitor_salaries', ['monitor_id'], unique=False)
    op.create_index(op.f('ix_monitor_salaries_tenant_id'), 'monitor_salaries', ['tenant_id'], unique=False)
    op.add_column('shifts', sa.Column('monitor_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_shifts_monitor_id'), 'shifts', ['monitor_id'], unique=False)
    op.create_foreign_key(None, 'shifts', 'users', ['monitor_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shifts', type_='foreignkey')
    op.drop_index(op.f('ix_shifts_monitor_id'), table_name='shifts')
    op.drop_column('shifts', 'monitor_id')
    op.drop_index(op.f('ix_monitor_salaries_tenant_id'), table_name='monitor_salaries')
    op.drop_index(op.f('ix_monitor_salaries_monitor_id'), table_name='monitor_salaries')
    op.drop_index(op.f('ix_monitor_salaries_effective_from'), table_name='monitor_salaries')
    op.drop_table('monitor_salaries')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_tenant_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_prefix'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
